{"name": "Test Case#3 Addition", "status": "failed", "statusDetails": {"message": "AssertionError: Subtraction failed\nassert (6 - 3) == 2", "trace": "@allure.title(\"Test Case#3 Addition\")\n    @allure.description(\"Verify sub functionality\")\n    @pytest.mark.snity\n    def test_subtraction3():\n>       assert 6 - 3 == 2, \"Subtraction failed\"\nE       AssertionError: Subtraction failed\nE       assert (6 - 3) == 2\n\ntest_automation\\test_Ex1.py:33: AssertionError"}, "description": "Verify sub functionality", "start": 1721974134314, "stop": 1721974134314, "uuid": "99331b2f-aa63-4c8e-a188-1d2778d7f679", "historyId": "33d6c900336038bc18d5a817d24a38a9", "testCaseId": "33d6c900336038bc18d5a817d24a38a9", "fullName": "test_automation.test_Ex1#test_subtraction3", "labels": [{"name": "tag", "value": "snity"}, {"name": "parentSuite", "value": "test_automation"}, {"name": "suite", "value": "test_Ex1"}, {"name": "host", "value": "DESKTOP-CECPEJJ"}, {"name": "thread", "value": "23136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_automation.test_Ex1"}]}